### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Jakousa** [Janikaka/Chess#1]
Ensimmäinen ladattu 1.12.2015 16:25, uusi versio ladattu 3.12.2015 17:14

Hyvän pituisia ja hyvin nimettyjä metodeja. Testit vaikuttivat keskeneräisiltä.
MCTS oli vielä kesken. Alpha-beta luokka on selkeä ja toteuttaa alpha-beta algoritmin ilman liikaa ylimääräistä.

Manuaalista kokeilua:
Pelasin itseäni vastaan ja musta kuningas katosi kun uhkasin sitä valkoisilla ja siirsin mustan lähetin kuningattaren tielle suojaamaan kuningasta. Väillä nappulat katoilivat
kun yritin ensin illegal movea ja sitten oikeata siirtoa.
Pelasin alpha-betaa vastaan ja ohjelma kysyi minulta miksi haluan sotilaan kasvattaa (Söin alkupelissä tornilla sotilaan keskikentältä), lisäksi torni liikkui yhden ruudun liian pitkälle,
kun yritän syödä vastustajan mustaa sotilasta niin peli kysyy toistuvasti miksi haluan korottaa sotilaan eikä anna pelin jatkua. Välillä peli antaa muuttaa joksikin nappulaksi, ei välttämättä
kuningattareksi mutta sain sotilasta siirtämällä pyydettyä peliä muuttamaan sotilas ratsuksi vaikka kuningatar ja muut eivät käyneet.
Alpha-beta myös hajosi jos yritti kasvattaa syvyyttä (syvyydellä 3) Syvyydellä 2 söin vastustajan nappulan ja oma nappulani siirtyi eri paikkaan kuin mistä söin.

Mukana kuvankaappaukset ja paintilla piirrettyjä reittejä mitä tehtiin ennen vuoroa.
![shakki syontisiirto](https://cloud.githubusercontent.com/assets/6400208/11565712/dfeb2448-99e7-11e5-8ba7-f2b8a17e85ab.png)

![shakki korotus](https://cloud.githubusercontent.com/assets/6400208/11565724/e6222ed8-99e7-11e5-8b40-e147c2d8d2e7.png)

![shakki siirto](https://cloud.githubusercontent.com/assets/6400208/11565725/e880bfb4-99e7-11e5-8dd9-bb84ab5f5a6a.png)

![shakki hajosi](https://cloud.githubusercontent.com/assets/6400208/11565726/e9c841da-99e7-11e5-9e96-6a7710a81a0e.png)

Luokassa board käytetään clone():a ja siihen voisi harkita kopiokonstruktoria. Sitä ymmärtääkseni pidetään huonohkona tapana, asiasta enemmän linkissä http://www.javapractices.com/topic/TopicAction.do;jsessionid=263CEEBD3E034E2C694A3D2297FF4F22?Id=71
Board luokassa moven sisällä kutsutaan kahdesti checkPromotion enkä löytänyt syytä sille, ehkä sen voisi vain kutsua joka vuoron lopussa? Tai aina kun siirtää sotilasta.

Luulen että shakin säännöissä on jotain häikkää kun sain bugeja aikaiseksi yksin pelatessa. Huomasin että olit päivittänyt MCTS tämän koodikatselmoinnin kirjoittamisen aikana
ja onnistuin toistamaan nuo kokeiluissa mainitsemat tapahtumat uudelleen. Huolestuin että ehkä tekoäly onnistuu tekemään luvattomia siirtoja kun se ihmispelaajaltakin onnistui.
Joitakin muita kummallisuuksia ihmettelin kuten abstraktia luokkaa AI, en löytänyt sille käyttötarkoitusta.

Käyttöliittymä alkaa näyttämään niin hyvältä että sillähän voisi ihan oikeasti pelata ajan kuluksi.

**Comment by Janikaka** [comment]
Kiitos Jami perusteellisesta koodikatselmoinnista!
